# Catppuccin Dawn!
colors:
  # Default colors
  primary:
    background: '0xFBF7F1'
    foreground: '0x575279'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xFBF7F1'
    cursor: '0x575279'

  # Normal colors
  normal:
    black:   '0xA09BAE'
    red:     '0xBB0D33'
    green:   '0x53A947'
    yellow:  '0xE49320'
    blue:    '0x3474EE'
    magenta: '0xEC83D0'
    cyan:    '0x209FB5'
    white:   '0x575279'

  # Bright colors
  bright:
    black:   '0xB2AEBC'
    red:     '0xBB0D33'
    green:   '0x53A947'
    yellow:  '0xE49320'
    blue:    '0x3474EE'
    magenta: '0xEC83D0'
    cyan:    '0x209FB5'
    white:   '0x575279'

  indexed_colors:
    - { index: 16, color: '0xDC907F' }
    - { index: 17, color: '0xDD7878' }

